"""add player table

Revision ID: 82ef0a33ca8f
Revises: 
Create Date: 2026-02-08 17:51:28.079156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82ef0a33ca8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    op.drop_table('player')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('squad_no', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('squad_no')

    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('position', sa.VARCHAR(length=20), nullable=False),
    sa.Column('nationality', sa.VARCHAR(length=30), nullable=False),
    sa.Column('goal', sa.INTEGER(), nullable=False),
    sa.Column('squad_no', sa.INTEGER(), nullable=True),
    sa.Column('img', sa.VARCHAR(length=255), nullable=False),
    sa.Column('club_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('club',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('stadium', sa.VARCHAR(length=50), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('logo', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('stadium')
    )
    # ### end Alembic commands ###
