"""Allow clean_sheets to be null

Revision ID: 9253f5f0fd30
Revises: 0d047c643a69
Create Date: 2026-02-11 14:32:22.568534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9253f5f0fd30'
down_revision = '0d047c643a69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('clean_sheets',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('clean_sheets',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
